#' GlobalEuphorbia feature dataset
#'
#' Dataset from Ernst et al. containing tandem MS data from various Euphorbia speciments
#'
#' @format Two matrices, one with feature intensities (GEfeatures) and cosine score matrix (GEcss)
#' \describe{
#'   \item{GEfeatures)}{Feature intensities}
#'   \item{GEcss}{Cosine score matrix (generated by GNPS)}
#'   ...
#' }
#' @source \url{https://github.com/DorresteinLaboratory/supplementary-GlobalEuphorbiaStudy}
"GEfeatures"
